name: Build java app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20'  # Встановлює Node.js 20


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          node-version: '20'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build java app
        run: ./gradlew build